### ISSUE TITLE
Setup CI/CD pipeline for dst-doc

### ISSUE THREAD

**Issue by choeppler** [direct-state-transfer/dst-doc#8]
Once the (build) infrastructure is in place (cf. #7), we should setup up a CI/CD pipeline for the docs repo, in a similar fashion as for the [dst-go](https://github.com/direct-state-transfer/dst-go) repository (cf. [direct-state-transfer/dst-go:#5](https://github.com/direct-state-transfer/dst-go/issues/5)).

I suggest two jobs:
- build any pull request (and configure passing build as mandatory check during review process)
- build and deploy merges into master

**Comment by anagha-ks** [comment]
Currently, the setup of environment is split between two files : `setup.sh` (install sphinx) and `deps.sh` (install plantuml). Since they perform the same function, both the scripts can be combined into a single file. 

Also in `setup.sh` missing dependencies are installed using apt package manager and in `deps.sh` a help message with instructions to install the missing dependencies is printed. 

This can be changed so that, in all cases, the missing package is installed using apt package manager.
Then, the same script can be used for setting up the environment in CI systems as well.
